### ISSUE TITLE
Path prefixes are not checked

### ISSUE THREAD

**Issue by PaulWay** [benkasminbullock/parse-gitignore#1]
`.gitignore` allows excluding entire directories via a path prefix - e.g. `bin/` - when given a trailing '/'.

These are not ignored in Parse::Gitignore.

**Comment by PaulWay** [comment]
See my pull request https://github.com/benkasminbullock/parse-gitignore/pull/2 for a test that should pass.

**Comment by benkasminbullock** [comment]
Please try the download of the latest version and see if it works.

Please use "perl Makefile.PL;make;make test" to install, ignore the file called "build.pl". This file may confuse cpan or cpanm clients.

**Comment by benkasminbullock** [comment]
I've fixed this in the commit

https://github.com/benkasminbullock/parse-gitignore/commit/32d5060de663ddbe0456b9d702aca6e7e3ed35aa

I'm closing this as fixed, please reopen if it doesn't work for you.

**Comment by benkasminbullock** [comment]
Are you doing anything with this project @PaulWay? 

I developed the module then found it didn't really work as well as I'd hoped, so I stopped using it. I'd uploaded it to CPAN in a moment of optimism, but I actually do not have any use for it and I probably should delete it from CPAN at some point. If you're thinking of using and improving it, then I will leave it, but I was quite surprised to get bug reports on this thing at this stage. Let me know.

**Comment by benkasminbullock** [comment]
Another thing I was going to do with this was use it to help in constructing Makefile target "make clean" using .gitignore to look for files which could be deleted. I think rather than delete this from cpan, I'll leave it there and hope that it provides some kind of avenue for improvement.

It's possible that there is some simple git command which makes this module completely redundant. Git documentation is beyond parody, so I won't be trying to work out what that might be.
